export const LOADER = 'https://www.portofastoria.com/pleasewait.htm'
export const GOOGLE = 'https://www.google.com'
export const YOUTUBE = 'https://www.youtube.com'
export const YOUTUBE_STUDIO = 'https://studio.youtube.com'
export const SELECT_ACCOUNT_YOUTUBE = 'https://www.youtube.com/signin?action_prompt_identity=true'
